spring.application.name=saas-subscription-core
# =========================================================================
# CONFIGURACIÓN DE LA BASE DE DATOS (MySQL)
# =========================================================================
# URL de conexión: apunta a tu máquina local (localhost) en el puerto estándar 3306
spring.datasource.url=jdbc:mysql://localhost:3306/saas_subscription_core?allowPublicKeyRetrieval=true&useSSL=false

# Credenciales de acceso a tu MySQL local
spring.datasource.username=root
spring.datasource.password=154115475Dc.

# El Driver que usa Java para saber el dialecto de comunicación con MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================================================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# =========================================================================
# "none" le dice a Hibernate que NO intente crear o modificar las tablas de la base de datos.
# Como somos universitarios rigurosos, nosotros controlamos las tablas con nuestro script SQL manual.
spring.jpa.hibernate.ddl-auto=none

# Muestra en la consola de IntelliJ las consultas SQL reales que Spring Boot ejecuta en segundo plano.
# Esto es vital para estudiar qué está haciendo el framework y aprender a optimizar.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true