spring.application.name=saas-subscription-core

# =========================================================================
# CONFIGURACION DE LA BASE DE DATOS (MySQL)
# =========================================================================
spring.datasource.url=jdbc:mysql://localhost:3306/saas_subscription_core?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=154115475Dc.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================================================================
# CONFIGURACION DE HIBERNATE / JPA
# =========================================================================
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de IntelliJ las consultas SQL reales
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true